// 56 Print all Subsequences of a string.

// Given a string, we have to find out all its subsequences of it. A String is a subsequence of a given String, that is generated by deleting some character of a given string without changing its order.

#include <bits/stdc++.h>
using namespace std;

// Time Complexity: O(2^n), where n is the size of the given string
// Auxiliary Space: O(2^n)
void func(string s, int i, string res, vector<string> &ans)
{
    if (i == s.size())
    {
        ans.push_back(res);
        return;
    }
    res.push_back(s[i]);
    func(s, i + 1, res, ans);
    res.pop_back();
    func(s, i + 1, res, ans);
}

vector<string> subsequences(string str)
{
    vector<string> ans;
    string result;
    func(str, 0, result, ans);
    return ans;
}

int main()
{
    string s;
    cin >> s;
    vector<string> ans = subsequences(s);
    for (auto ele : ans)
        cout << ele << ' ';
}